name: SonarQube Analysis (Node.js)

on: push

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Probar conexión a SonarQube
        run: curl -I http://34.58.56.21:9000
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install 

      - name: Run tests and generate coverage
        run: npm run test -- --coverage.provider c8

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=My-project-dev \
            -Dsonar.host.url=http://34.58.56.21:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=src \
            -Dsonar.tests=test \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

